name: build and deploy helloworld container
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        run: |
          cd action-a
          docker build -t seventyb/helloworld .
          docker save -o ../helloworld.tar seventyb/helloworld
      - name: scp docker image to my host
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          port: 22
          source: helloworld.tar
          target: /tmp
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          port: 22
          script: |
            docker load -i /tmp/helloworld.tar
            rm /tmp/helloworld.tar
            #docker kill $(docker ps -q)
            docker run -d seventyb/helloworld:latest
            #docker system prune -f
