name: A workflow for my Hello World file
on:
  pull_request:
    types:
      - ready_for_review
      - opened
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
