name: A workflow for my Hello World file
on:
  pull_request:
    types:
      - labeled
    
jobs:
  build:
    name: Hello world action
    if: github.event.label.name == 'build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
