name: Workflow for main branch
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    name: Main action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "main"
