name: Workflow for testing branch when PR closed
on:
  pull_request:
    types:
      - closed
    branches:
      - testing

jobs:
  build:
    name: Testing action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "testing"
