name: A workflow for my Hello World file (testing)
on:
  pull_request:
    types:
      - closed
    branches:
      - testing

jobs:
  build:
    name: Hello world testing action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "testing"
